image: python:3.6
stages:
  - test
test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - apt-get install pylint -y
    - pip install -U pytest
    - cd src && pytest
